(ns wagoe.email.core.email
  "Core email processing functions.

   Pure functions for preparing, validating, and formatting emails.
   No side effects - all I/O happens in the shell layer."
  (:require [clojure.string :as str]))

;; =============================================================================
;; Email Address Validation
;; =============================================================================

(def ^:private email-address-pattern
  "Basic RFC 5322 email address pattern."
  #"^[a-zA-Z0-9._%+-]+@[a-zA-Z0-9.-]+\.[a-zA-Z]{2,}$")

(defn valid-email-address?
  "Check if string is valid email format (basic RFC 5322).

   Args:
     email - Email address string

   Returns:
     true if valid email format, false otherwise"
  [email]
  (and (string? email)
       (boolean (re-matches email-address-pattern email))))

(defn validate-recipients
  "Validate recipient email addresses (pure function).

   Args:
     recipients - Vector of email address strings or single email string

   Returns:
     Map with:
       :valid? - Boolean indicating if all emails are valid
       :valid-emails - Vector of valid email addresses
       :invalid-emails - Vector of invalid email addresses"
  [recipients]
  (let [recipient-list (if (string? recipients)
                         [recipients]
                         (vec recipients))
        grouped (group-by valid-email-address? recipient-list)]
    {:valid? (empty? (get grouped false []))
     :valid-emails (vec (get grouped true []))
     :invalid-emails (vec (get grouped false []))}))

;; =============================================================================
;; Header Formatting
;; =============================================================================

(defn format-headers
  "Format and normalize email headers (pure function).

   Args:
     headers - Map of header key-value pairs

   Returns:
     Normalized headers map with kebab-case keys"
  [headers]
  (when headers
    (into {}
          (map (fn [[k v]]
                 [(if (keyword? k) k (keyword k))
                  (str v)])
               headers))))

;; =============================================================================
;; Email Preparation
;; =============================================================================

(defn normalize-recipients
  "Normalize recipients to vector format.

   Args:
     recipients - String or vector of email addresses

   Returns:
     Vector of email addresses"
  [recipients]
  (if (string? recipients)
    [recipients]
    (vec recipients)))

(defn prepare-email
  "Prepare email for sending (pure function).

   Args:
     email-input - Map with required keys:
                   :to - Email address or vector of addresses
                   :from - Email address
                   :subject - Email subject
                   :body - Email body
                   Optional keys:
                   :headers - Map of email headers
                   :attachments - Vector of attachment maps
                   :metadata - Map of metadata
     email-id - UUID generated by shell layer
     now - Current timestamp generated by shell layer

   Returns:
     Email map with:
       :id - Generated UUID
       :to - Normalized vector of recipients
       :from - From address
       :subject - Subject line
       :body - Email body
       :headers - Normalized headers (if provided)
       :attachments - Attachments (if provided)
       :metadata - Metadata (if provided)
       :created-at - Timestamp of creation"
  [email-input email-id now]
  (let [normalized-to (normalize-recipients (:to email-input))]
    (cond-> {:id email-id
             :to normalized-to
             :from (:from email-input)
             :subject (:subject email-input)
             :body (:body email-input)
             :created-at now}

      (:headers email-input)
      (assoc :headers (format-headers (:headers email-input)))

      (:attachments email-input)
      (assoc :attachments (:attachments email-input))

      (:metadata email-input)
      (assoc :metadata (:metadata email-input)))))

;; =============================================================================
;; Email Validation
;; =============================================================================

(defn validate-email
  "Validate complete email structure (pure function).

   Args:
     email - Email map

   Returns:
     Map with:
       :valid? - Boolean indicating validity
       :errors - Vector of error messages (if invalid)"
  [email]
  (let [errors (cond-> []
                 (not (:to email))
                 (conj "Missing required field: to")

                 (not (:from email))
                 (conj "Missing required field: from")

                 (not (:subject email))
                 (conj "Missing required field: subject")

                 (not (:body email))
                 (conj "Missing required field: body")

                 (and (:to email)
                      (not (valid-email-address? (:from email))))
                 (conj "Invalid from email address")

                 (and (:to email)
                      (let [validation (validate-recipients (:to email))]
                        (not (:valid? validation))))
                 (conj "Invalid recipient email addresses"))]
    {:valid? (empty? errors)
     :errors errors}))

;; =============================================================================
;; Email Utilities
;; =============================================================================

(defn email-summary
  "Create summary of email for logging/monitoring (pure function).

   Args:
     email - Email map

   Returns:
     Summary map with key fields"
  [email]
  {:id (:id email)
   :to (count (:to email))
   :from (:from email)
   :subject (:subject email)
   :has-attachments? (boolean (seq (:attachments email)))
   :created-at (:created-at email)})

(defn add-reply-to
  "Add Reply-To header to email (pure function).

   Args:
     email - Email map
     reply-to - Reply-to email address

   Returns:
     Email map with Reply-To header added"
  [email reply-to]
  (let [current-headers (or (:headers email) {})
        updated-headers (assoc current-headers :reply-to reply-to)]
    (assoc email :headers updated-headers)))

(defn add-cc
  "Add CC recipients to email (pure function).

   Args:
     email - Email map
     cc-recipients - Email address or vector of addresses

   Returns:
     Email map with CC header added"
  [email cc-recipients]
  (let [normalized-cc (normalize-recipients cc-recipients)
        current-headers (or (:headers email) {})
        updated-headers (assoc current-headers :cc (str/join ", " normalized-cc))]
    (assoc email :headers updated-headers)))

(defn add-bcc
  "Add BCC recipients to email (pure function).

   Args:
     email - Email map
     bcc-recipients - Email address or vector of addresses

   Returns:
     Email map with BCC header added"
  [email bcc-recipients]
  (let [normalized-bcc (normalize-recipients bcc-recipients)
        current-headers (or (:headers email) {})
        updated-headers (assoc current-headers :bcc (str/join ", " normalized-bcc))]
    (assoc email :headers updated-headers)))
