(ns wagoe.reports.shell.adapters.pdf-test
  "Integration tests for the OpenHTMLtoPDF adapter.
   Generates real PDF bytes — verifies %%PDF- magic bytes."
  (:require [wagoe.reports.shell.adapters.pdf :as sut]
            [wagoe.reports.ports :as ports]
            [clojure.test :refer [deftest is testing]]))

;; =============================================================================
;; Helpers
;; =============================================================================

(def ^:private sample-template-report
  {:id       :pdf-test-template
   :type     :pdf
   :page-size :a4
   :filename "test-output.pdf"
   :template (fn [data]
               [:html
                [:head [:title "Test Report"]]
                [:body
                 [:h1 "Test Report"]
                 [:p "Generated by wagoe-reports"]
                 [:table
                  [:thead [:tr [:th "Name"] [:th "Value"]]]
                  [:tbody
                   (map (fn [{:keys [name value]}]
                          [:tr [:td name] [:td (str value)]])
                        data)]]]])})

(def ^:private sample-sections-report
  {:id       :pdf-test-sections
   :type     :pdf
   :sections [{:type    :header
               :content [:h1 "Sections Report"]}
              {:type    :table
               :columns [{:key :product :label "Product"}
                         {:key :qty     :label "Qty"     :format :number}
                         {:key :price   :label "Price"   :format :currency}]}
              {:type :spacer}
              {:type    :footer
               :content [:p "End of report"]}]})

(def ^:private sample-data
  [{:name "Widget A" :value 42 :product "Widget A" :qty 5  :price 9.99}
   {:name "Widget B" :value 17 :product "Widget B" :qty 12 :price 3.50}])

;; =============================================================================
;; Tests
;; =============================================================================

(deftest ^:integration pdf-magic-bytes-template-test
  (testing "template-based report produces valid PDF bytes"
    (let [gen    (sut/create-pdf-generator)
          result (ports/generate! gen sample-template-report sample-data {})]
      (is (some? (:bytes result)))
      (is (pos? (count (:bytes result))))
      ;; PDF magic bytes: 25 50 44 46 2d  (%PDF-)
      (is (= (int \%) (aget ^bytes (:bytes result) 0)))
      (is (= (int \P) (aget ^bytes (:bytes result) 1)))
      (is (= (int \D) (aget ^bytes (:bytes result) 2)))
      (is (= (int \F) (aget ^bytes (:bytes result) 3))))))

(deftest ^:integration pdf-filename-default-test
  (testing "filename defaults to <id>.pdf when not specified"
    (let [gen    (sut/create-pdf-generator)
          defn   {:id :my-report :type :pdf :template (fn [_] [:html [:body [:p "hi"]]])}
          result (ports/generate! gen defn nil {})]
      (is (= "my-report.pdf" (:filename result)))))
  (testing "explicit filename is used"
    (let [gen    (sut/create-pdf-generator)
          result (ports/generate! gen sample-template-report sample-data {})]
      (is (= "test-output.pdf" (:filename result))))))

(deftest ^:integration pdf-sections-based-test
  (testing "sections-based report produces valid PDF bytes"
    (let [gen    (sut/create-pdf-generator)
          result (ports/generate! gen sample-sections-report sample-data {})]
      (is (pos? (count (:bytes result))))
      (is (= (int \%) (aget ^bytes (:bytes result) 0))))))

(deftest ^:unit pdf-supported-type-test
  (testing "supported-type? returns true for :pdf"
    (is (ports/supported-type? (sut/create-pdf-generator) :pdf)))
  (testing "supported-type? returns false for :excel"
    (is (not (ports/supported-type? (sut/create-pdf-generator) :excel)))))

(deftest ^:integration pdf-type-in-output-test
  (testing ":type is :pdf in output"
    (let [gen    (sut/create-pdf-generator)
          result (ports/generate! gen sample-template-report sample-data {})]
      (is (= :pdf (:type result))))))
