(ns wagoe.reports.shell.adapters.word-test
  "Integration tests for the Apache POI XWPF Word adapter.
   Generates real DOCX bytes — verifies ZIP magic bytes (DOCX = ZIP container)."
  (:require [wagoe.reports.shell.adapters.word :as sut]
            [wagoe.reports.ports :as ports]
            [clojure.test :refer [deftest is testing]])
  (:import [java.util.zip ZipInputStream]
           [java.io ByteArrayInputStream]))

;; =============================================================================
;; Helpers
;; =============================================================================

(def ^:private sample-sections-report
  {:id       :word-test-sections
   :type     :word
   :filename "test-output.docx"
   :sections [{:type    :header
               :content "Quarterly Report"}
              {:type    :paragraph
               :content "This report covers Q1 2026 sales figures."}
              {:type    :table
               :columns [{:key :product  :label "Product"}
                         {:key :quantity :label "Qty"     :format :number}
                         {:key :revenue  :label "Revenue" :format :currency}]}
              {:type :spacer}
              {:type    :footer
               :content "Generated by boundary-reports"}]})

(def ^:private sample-data
  [{:product "Alpha"  :quantity 10 :revenue 199.90}
   {:product "Beta"   :quantity 5  :revenue 499.50}
   {:product "Gamma"  :quantity 3  :revenue  13.47}])

;; =============================================================================
;; ZIP / DOCX helpers
;; =============================================================================

(defn- docx-magic? [^bytes bytes]
  ;; DOCX is a ZIP file. ZIP magic: 50 4B 03 04
  (and (>= (count bytes) 4)
       (= (aget bytes 0) (byte 0x50))  ; P
       (= (aget bytes 1) (byte 0x4B))  ; K
       (= (aget bytes 2) (byte 0x03))
       (= (aget bytes 3) (byte 0x04))))

(defn- read-zip-entry [^bytes bs entry-name]
  (with-open [zis (ZipInputStream. (ByteArrayInputStream. bs))]
    (loop []
      (when-let [e (.getNextEntry zis)]
        (if (= (.getName e) entry-name)
          (slurp zis)
          (recur))))))

;; =============================================================================
;; Tests
;; =============================================================================

(deftest ^:integration word-magic-bytes-test
  (testing "sections-based report produces valid DOCX bytes"
    (let [gen    (sut/create-word-generator)
          result (ports/generate! gen sample-sections-report sample-data {})]
      (is (some? (:bytes result)))
      (is (pos? (count (:bytes result))))
      (is (docx-magic? (:bytes result))))))

(deftest ^:integration word-filename-default-test
  (testing "filename defaults to <id>.docx when not specified"
    (let [gen  (sut/create-word-generator)
          defn {:id       :my-word-report
                :type     :word
                :sections [{:type    :header
                            :content "Hello"}]}
          result (ports/generate! gen defn [] {})]
      (is (= "my-word-report.docx" (:filename result)))))
  (testing "explicit filename is used"
    (let [gen    (sut/create-word-generator)
          result (ports/generate! gen sample-sections-report sample-data {})]
      (is (= "test-output.docx" (:filename result))))))

(deftest ^:unit word-supported-type-test
  (testing "supported-type? returns true for :word"
    (is (ports/supported-type? (sut/create-word-generator) :word)))
  (testing "supported-type? returns false for :pdf"
    (is (not (ports/supported-type? (sut/create-word-generator) :pdf)))))

(deftest ^:integration word-type-in-output-test
  (testing ":type is :word in output"
    (let [gen    (sut/create-word-generator)
          result (ports/generate! gen sample-sections-report sample-data {})]
      (is (= :word (:type result))))))

(deftest ^:integration word-empty-sections-test
  (testing "report with no sections still produces valid DOCX bytes"
    (let [gen    (sut/create-word-generator)
          report {:id   :empty-word
                  :type :word}
          result (ports/generate! gen report [] {})]
      (is (docx-magic? (:bytes result))))))

(deftest ^:integration word-deterministic-output-test
  (testing "same input always produces identical bytes"
    (let [gen     (sut/create-word-generator)
          result1 (ports/generate! gen sample-sections-report sample-data {})
          _       (Thread/sleep 1100)
          result2 (ports/generate! gen sample-sections-report sample-data {})]
      (is (= (seq (:bytes result1)) (seq (:bytes result2))))))

  (testing "core.xml created timestamp is pinned to epoch (not dynamic)"
    (let [gen      (sut/create-word-generator)
          result   (ports/generate! gen sample-sections-report sample-data {})
          core-xml (read-zip-entry (:bytes result) "docProps/core.xml")]
      (is (re-find #"1970-01-01T00:00:00Z" core-xml)
          "dcterms:created must be pinned to epoch, not the current clock"))))
