(ns shop.product.shell.module-wiring
  "Integrant wiring for the product module.

   Generated by `bb scaffold`. `bb scaffold integrate` writes the config key
   that activates this module; these methods are what that key resolves to.

   Components:
     :wagoe/product-repository  persistence, on the shared :wagoe/db-context
     :wagoe/product-service     business logic, on the repository
     :wagoe/product-routes      HTTP routes, on the service
     :wagoe/product            the module itself — what discovery looks for"
  (:require [shop.product.shell.http :as http]
            [shop.product.shell.persistence :as persistence]
            [shop.product.shell.service :as service]
            [clojure.tools.logging :as log]
            [integrant.core :as ig]))

;; =============================================================================
;; Repository
;; =============================================================================

(defmethod ig/init-key :wagoe/product-repository
  [_ {:keys [ctx]}]
  (log/info "Initializing product repository")
  (persistence/create-repository ctx))

(defmethod ig/halt-key! :wagoe/product-repository
  [_ _repository]
  (log/info "product repository halted"))

;; =============================================================================
;; Service
;; =============================================================================

(defmethod ig/init-key :wagoe/product-service
  [_ {:keys [repository]}]
  (log/info "Initializing product service")
  (service/create-service repository))

(defmethod ig/halt-key! :wagoe/product-service
  [_ _service]
  (log/info "product service halted"))

;; =============================================================================
;; Routes
;; =============================================================================

(defmethod ig/init-key :wagoe/product-routes
  [_ {:keys [service config]}]
  (log/info "Initializing product routes")
  ;; A contribution — {:api [...] :web [...] :static [...]} — not a route
  ;; table. :wagoe/http-handler prefixes and versions each part before
  ;; mounting it.
  (http/product-routes service (or config {})))

(defmethod ig/halt-key! :wagoe/product-routes
  [_ _routes]
  (log/info "product routes halted"))

;; =============================================================================
;; The module
;; =============================================================================
;;
;; The key module discovery looks for. `bb scaffold integrate` writes it to the
;; :active section of config.edn, ig-config turns it into the components below,
;; and the app hands :wagoe/product-routes to the HTTP handler as one of
;; :module-routes. Setting :enabled? false in config.edn switches the module off
;; without deleting anything.

(defmethod ig/init-key :wagoe/product
  [_ {:keys [routes service enabled?]}]
  (if (false? enabled?)
    (do (log/info "product module disabled") nil)
    (do (log/info "product module enabled")
        {:routes routes :service service})))

(defmethod ig/halt-key! :wagoe/product
  [_ _module]
  (log/info "product module halted"))
