(ns wagoe.tenant.core.membership)

(defn prepare-invitation*
  "Creates a new membership map in :invited status using explicit runtime inputs.

   Args:
     membership-id - UUID generated by the imperative shell
     user-id       - UUID of the user being invited
     tenant-id     - UUID of the tenant
     role          - one of :admin :member :viewer :contractor
     now           - java.time.Instant for timestamp fields

   Returns:
     New membership map ready for persistence."
  [membership-id user-id tenant-id role now]
  {:id          membership-id
   :tenant-id   tenant-id
   :user-id     user-id
   :role        role
   :status      :invited
   :invited-at  now
   :accepted-at nil
   :created-at  now
   :updated-at  nil})

(defn prepare-active-membership*
  "Creates a new membership map directly in :active status using explicit runtime inputs.

   Intended for initial tenant bootstrap flows where the first member
   should become active immediately after account verification.

   Args:
     membership-id - UUID generated by the imperative shell
     user-id       - UUID of the user
     tenant-id     - UUID of the tenant
     role          - one of :admin :member :viewer :contractor
     now           - java.time.Instant for timestamp fields

   Returns:
     New active membership map ready for persistence."
  [membership-id user-id tenant-id role now]
  {:id          membership-id
   :tenant-id   tenant-id
   :user-id     user-id
   :role        role
   :status      :active
   :invited-at  now
   :accepted-at now
   :created-at  now
   :updated-at  nil})

(defn accept-invitation
  "Transitions a membership from :invited to :active.

   Args:
     membership - existing membership map
     now        - java.time.Instant for timestamp fields

   Returns:
     Updated membership map with :active status and accepted-at set."
  [membership now]
  (assoc membership
         :status      :active
         :accepted-at now
         :updated-at  now))

(defn suspend-membership
  "Transitions a membership to :suspended status.

   Args:
     membership - existing membership map
     now        - java.time.Instant for timestamp fields

   Returns:
     Updated membership map with :suspended status."
  [membership now]
  (assoc membership
         :status     :suspended
         :updated-at now))

(defn revoke-membership
  "Transitions a membership to :revoked status.

   Args:
     membership - existing membership map
     now        - java.time.Instant for timestamp fields

   Returns:
     Updated membership map with :revoked status."
  [membership now]
  (assoc membership
         :status     :revoked
         :updated-at now))

(defn update-role
  "Updates the role on a membership.

   Args:
     membership - existing membership map
     role       - new role keyword
     now        - java.time.Instant for timestamp fields

   Returns:
     Updated membership map with new role."
  [membership role now]
  (assoc membership
         :role       role
         :updated-at now))

(defn active-member?
  "Returns true when the membership status is :active."
  [membership]
  (= :active (:status membership)))

(defn has-role?
  "Returns true when the membership role is in allowed-roles.

   Args:
     membership    - membership map
     allowed-roles - set (or collection) of allowed role keywords

   Returns:
     Boolean."
  [membership allowed-roles]
  (contains? (set allowed-roles) (:role membership)))
