-- Boundary Conjure configuration
-- Add to your init.lua or init.vim:
--
-- vim.g["conjure#client#clojure#nrepl#connection#auto_repl#enabled"] = true
-- vim.g["conjure#client#clojure#nrepl#connection#auto_repl#port"] = 7888
-- vim.g["conjure#client#clojure#nrepl#eval#auto_require"] = true
--
-- Start REPL: clojure -M:repl-clj
-- Then in nvim: :ConjureConnect 7888
--
-- Useful mappings:
--   <localleader>ee  - Evaluate expression
--   <localleader>eb  - Evaluate buffer
--   <localleader>er  - Evaluate root form
