#!/usr/bin/env bb
;; libs/tools/src/wagoe/tools/quickstart.clj
;;
;; Quickstart — one command from clone to running app.
;;
;; Usage (via bb.edn task):
;;   bb quickstart                  # Interactive quickstart
;;   bb quickstart --preset minimal # Non-interactive with minimal preset

(ns wagoe.tools.quickstart
  (:require [wagoe.tools.ansi :refer [bold green red dim]]
            [babashka.process :as process]
            [clojure.java.io :as io]
            [clojure.string :as str]))

;; =============================================================================
;; Presets — named onboarding profiles mapping to concrete setup flags
;; =============================================================================

(def presets
  {"minimal"  {:database "h2"         :description "H2 in-memory, no extras"}
   "standard" {:database "postgresql" :description "PostgreSQL, recommended for production"}
   "sqlite"   {:database "sqlite"     :description "SQLite file-based, zero-config"}
   "mysql"    {:database "mysql"      :description "MySQL/MariaDB"}})

(defn- resolve-preset
  "Resolve a preset name to setup flags. Returns nil if unknown."
  [preset-name]
  (get presets preset-name))

;; =============================================================================
;; Config injection — adds Integrant key to config.edn :active section
;; =============================================================================

(def ^:private sample-config-snippet
  "Integrant config snippet for the sample tasks module."
  (str "\n  ;; Tasks module (generated by quickstart)\n"
       "  :wagoe/tasks\n"
       "  {:enabled? true\n"
       "   :base-path \"/api/tasks\"}\n"))

(defn- find-active-closing-brace
  "Find the index of the closing brace of the :active section using
   brace-balanced walking. Returns the index in the original text, or nil."
  [text]
  ;; Find :active keyword in the text (not inside comments)
  (let [active-idx (loop [pos 0]
                     (let [idx (str/index-of text ":active" pos)]
                       (cond
                         (nil? idx) nil
                         ;; Skip if inside a comment (check if line starts with ;)
                         (let [line-start (let [li (.lastIndexOf ^String text "\n" (int idx))]
                                            (if (neg? li) 0 li))
                               line-text  (str/trim (subs text line-start idx))]
                           (str/starts-with? line-text ";"))
                         (recur (+ idx 7))
                         ;; Skip :inactive
                         (str/starts-with? (subs text idx) ":inactive")
                         (recur (+ idx 9))
                         :else idx)))]
    (when active-idx
      ;; Find the opening { of the :active value (skip past ":active\n {")
      (let [open-idx (str/index-of text "{" (+ active-idx 7))]
        (when open-idx
          (loop [i     (inc open-idx)
                 depth 1]
            (cond
              (>= i (count text)) nil
              (zero? depth)       (dec i)
              :else (let [c (nth text i)]
                      (recur (inc i)
                             (case c \{ (inc depth) \} (dec depth) depth))))))))))

(defn- paren-repair
  "Run clj-paren-repair on a file to fix any brace/paren imbalance."
  [config-path]
  (try
    (process/shell {:continue true :out :string :err :string}
                   "clj-paren-repair" config-path)
    (catch Exception _ nil)))

(defn- inject-module-config
  "Inject the sample module Integrant config into a config.edn file.
   Uses brace-balanced walking to find the :active section's closing brace,
   inserts the snippet before it, then runs clj-paren-repair as a safety net.
   Returns true if injection succeeded."
  [config-path]
  (let [f (io/file config-path)]
    (when (.exists f)
      (let [text (slurp f)]
        (if (str/includes? text ":wagoe/tasks")
          true ;; already present
          (let [brace-idx (find-active-closing-brace text)]
            (if brace-idx
              (let [new-text (str (subs text 0 brace-idx)
                                  sample-config-snippet
                                  (subs text brace-idx))]
                (spit config-path new-text)
                (paren-repair config-path)
                true)
              false)))))))

(defn inject-sample-module-config
  "Inject the sample tasks module config into dev and test config.edn files."
  []
  (let [root    (System/getProperty "user.dir")
        dev-ok  (inject-module-config (str root "/resources/conf/dev/config.edn"))
        test-ok (inject-module-config (str root "/resources/conf/test/config.edn"))]
    (and dev-ok test-ok)))

;; =============================================================================
;; Step runner
;; =============================================================================

(defn- run-step
  "Run a named step. Returns true if successful."
  [step-num total description cmd & {:keys [continue?]}]
  (println)
  (println (bold (str "[" step-num "/" total "] " description)))
  (println (dim (str "  $ " (str/join " " cmd))))
  (let [result (apply process/shell {:continue true} cmd)
        ok?    (zero? (:exit result))]
    (if ok?
      (println (green "  Done"))
      (do (println (red "  Failed"))
          (when-not continue?
            (println (red "\nQuickstart aborted. Fix the issue above and re-run bb quickstart."))
            (System/exit 1))))
    ok?))

;; =============================================================================
;; Main flow
;; =============================================================================

(defn- print-banner []
  (println)
  (println (bold "━━━ Boundary Quickstart ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"))
  (println)
  (println "  This will set up a complete Boundary development environment.")
  (println "  Steps: check environment, configure, scaffold, migrate, start.")
  (println))

(defn- print-success []
  (println)
  (println (green (bold "━━━ Quickstart Complete ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━")))
  (println)
  (println (green "  Your Boundary project is configured and ready to start!"))
  (println)
  (println "  Next steps:")
  (println "    1. Start the REPL:  " (bold "clojure -M:repl") "  (headless nREPL on port 7888)")
  (println "    2. Connect your editor (or the Boundary MCP server) and eval " (bold "(go)"))
  (println "    3. The startup dashboard will show you the URLs and ports")
  (println)
  (println "  Useful commands:")
  (println "    " (bold "bb scaffold") "   — create more modules")
  (println "    " (bold "bb guide") "      — contextual help and guidance")
  (println "    " (bold "(status)") "      — in the REPL, show URLs and health")
  (println "    " (bold "(commands)") "    — in the REPL, see all helpers")
  (println))

(defn -main [& args]
  (let [preset-idx (.indexOf (vec args) "--preset")
        preset-name (when (and (>= preset-idx 0) (< (inc preset-idx) (count args)))
                      (nth args (inc preset-idx)))
        preset      (when preset-name (resolve-preset preset-name))]
    (when (and preset-name (not preset))
      (println (red (str "Unknown preset: " preset-name)))
      (println (dim (str "Available presets: " (str/join ", " (sort (keys presets))))))
      (System/exit 1))

    (print-banner)

    ;; Step 1: Check environment prerequisites (critical — abort on failure)
    (run-step 1 8 "Checking development environment"
              ["bb" "doctor:env" "--ci"])

    ;; Step 2: Run setup
    (if preset
      (do (println (dim (str "\n  Using preset: " preset-name " (" (:description preset) ")")))
          (run-step 2 8 "Running configuration setup"
                    ["bb" "setup" "--database" (:database preset)]))
      (run-step 2 8 "Running configuration setup"
                ["bb" "setup"]))

    ;; Step 3: Validate configuration (critical — abort on failure)
    (run-step 3 8 "Validating configuration"
              ["bb" "doctor" "--ci"])

    ;; Step 4: Scaffold and integrate a sample module (non-critical — continue on failure)
    (let [scaffolded? (run-step 4 8 "Scaffolding sample module"
                                ["bb" "scaffold" "generate"
                                 "--module-name" "tasks" "--entity" "Task"
                                 "--field" "title:string" "--field" "done:boolean"]
                                :continue? true)]
      (when scaffolded?
        (run-step 5 8 "Integrating sample module into project"
                  ["bb" "scaffold" "integrate" "tasks"]
                  :continue? true)
        ;; Step 6: Activate module in config — the part integrate leaves manual
        (println)
        (println (bold (str "[6/8] Activating sample module in config")))
        (if (inject-sample-module-config)
          (println (green "  Done"))
          (println (dim "  Skipped — could not inject config (add :wagoe/tasks manually)")))))

    ;; Step 7: Run migrations (critical — abort on failure)
    (run-step 7 8 "Running database migrations"
              ["bb" "migrate" "up"])

    ;; Step 8: Verify project structure
    (run-step 8 8 "Verifying project structure"
              ["bb" "smoke-check"])

    (print-success)))

;; Run when executed directly
(when (= *file* (System/getProperty "babashka.file"))
  (apply -main *command-line-args*))
