#!/usr/bin/env bb
;; libs/tools/src/wagoe/tools/quickstart.clj
;;
;; Quickstart — one command from clone to running app.
;;
;; Usage (via bb.edn task):
;;   bb quickstart                  # Interactive quickstart
;;   bb quickstart --preset minimal # Non-interactive with minimal preset

(ns wagoe.tools.quickstart
  (:require [wagoe.tools.ansi :refer [bold green red dim]]
            [wagoe.tools.config-edn :as config-edn]
            [babashka.process :as process]
            [clojure.java.io :as io]
            [clojure.string :as str]))

;; =============================================================================
;; Presets — named onboarding profiles mapping to concrete setup flags
;; =============================================================================

(def presets
  ;; H2 is file-backed in dev. It was in-memory until BOU-265, which made this
  ;; preset unable to produce a working app: migrate, create-admin and the
  ;; server are separate JVMs, and an in-memory H2 is private to each.
  {"minimal"  {:database "h2"         :description "H2 file-based, no extras"}
   "standard" {:database "postgresql" :description "PostgreSQL, recommended for production"}
   "sqlite"   {:database "sqlite"     :description "SQLite file-based, zero-config"}
   "mysql"    {:database "mysql"      :description "MySQL/MariaDB"}})

(defn- resolve-preset
  "Resolve a preset name to setup flags. Returns nil if unknown."
  [preset-name]
  (get presets preset-name))

;; =============================================================================
;; Config injection — adds Integrant key to config.edn :active section
;; =============================================================================

(def ^:private sample-config-snippet
  "Integrant config snippet for the sample tasks module."
  (str "\n  ;; Tasks module (generated by quickstart)\n"
       "  :wagoe/tasks\n"
       "  {:enabled? true\n"
       "   :base-path \"/api/tasks\"}\n"))

(defn inject-sample-module-config
  "Inject the sample tasks module config into dev and test config.edn files.

   The text editing lives in wagoe.tools.config-edn — `bb scaffold integrate`
   needs the same thing for an arbitrary module, and two copies of an editor for
   one file is how they drift (BOU-310)."
  []
  (let [root (System/getProperty "user.dir")]
    (every? #(contains? #{:written :already-present}
                        (config-edn/inject-key!
                         (str root "/resources/conf/" % "/config.edn")
                         ":wagoe/tasks" sample-config-snippet {}))
            ["dev" "test"])))

;; =============================================================================
;; Step runner
;; =============================================================================

(defn- existing-dev-config?
  "True when the project already has a dev config written by `wagoe new`.
   Used to skip the setup wizard rather than overwrite working configuration."
  []
  (.exists (io/file "resources/conf/dev/config.edn")))

(defn- run-step
  "Run a named step. Returns true if successful."
  [step-num total description cmd & {:keys [continue?]}]
  (println)
  (println (bold (str "[" step-num "/" total "] " description)))
  (println (dim (str "  $ " (str/join " " cmd))))
  (let [result (apply process/shell {:continue true} cmd)
        ok?    (zero? (:exit result))]
    (if ok?
      (println (green "  Done"))
      (do (println (red "  Failed"))
          (when-not continue?
            (println (red "\nQuickstart aborted. Fix the issue above and re-run bb quickstart."))
            (System/exit 1))))
    ok?))

;; =============================================================================
;; Main flow
;; =============================================================================

(defn- print-banner []
  (println)
  (println (bold "━━━ Wagoe Quickstart ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"))
  (println)
  (println "  This will set up a complete Wagoe development environment.")
  ;; Says "verify", not "start". Quickstart does not launch the app — it ends
  ;; by telling you to run `clojure -M:repl` and eval (go). Claiming "start"
  ;; left users expecting a running server after 8/8 Done, and looking for a
  ;; failure that had not happened.
  (println "  Steps: check environment, configure, scaffold, migrate, verify.")
  (println "  It does not start the app — the final step tells you how.")
  (println))

(defn- print-success []
  (println)
  (println (green (bold "━━━ Quickstart Complete ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━")))
  (println)
  (println (green "  Your Wagoe project is configured and ready to start!"))
  (println)
  (println "  Next steps:")
  (println "    1. Start the REPL:  " (bold "clojure -M:repl") "  (headless nREPL on port 7888)")
  (println "    2. Connect your editor (or the Wagoe MCP server) and eval " (bold "(go)"))
  (println "    3. The startup dashboard will show you the URLs and ports")
  (println)
  (println "  Useful commands:")
  (println "    " (bold "bb scaffold") "   — create more modules")
  (println "    " (bold "bb guide") "      — contextual help and guidance")
  (println "    " (bold "(status)") "      — in the REPL, show URLs and health")
  (println "    " (bold "(commands)") "    — in the REPL, see all helpers")
  (println))

(defn -main [& args]
  (let [preset-idx (.indexOf (vec args) "--preset")
        preset-name (when (and (>= preset-idx 0) (< (inc preset-idx) (count args)))
                      (nth args (inc preset-idx)))
        preset      (when preset-name (resolve-preset preset-name))]
    (when (and preset-name (not preset))
      (println (red (str "Unknown preset: " preset-name)))
      (println (dim (str "Available presets: " (str/join ", " (sort (keys presets))))))
      (System/exit 1))

    (print-banner)

    ;; Step 1: Check environment prerequisites (critical — abort on failure)
    (run-step 1 8 "Checking development environment"
              ["bb" "doctor:env" "--ci"])

    ;; Step 2: Run setup — but never over a config that already works.
    ;;
    ;; `wagoe new` writes a valid dev config, and re-running the wizard on top
    ;; of it could only make a first run worse: the wizard rewrites
    ;; resources/conf/dev/config.edn, and an EOF stdin (CI, `</dev/null`) or a
    ;; user pressing Enter took its first option. That turned a working project
    ;; into one pointing at a database server nobody had installed, and the
    ;; migration step then died on ClassNotFoundException (BOU-228).
    ;;
    ;; An explicit --preset still runs setup: asking for a preset is asking to
    ;; change the config.
    (cond
      preset
      (do (println (dim (str "\n  Using preset: " preset-name " (" (:description preset) ")")))
          (run-step 2 8 "Running configuration setup"
                    ["bb" "setup" "--database" (:database preset)]))

      (existing-dev-config?)
      (println (str "\n" (bold "[2/8] Running configuration setup") "\n"
                    (dim "  Existing config found at resources/conf/dev/config.edn — keeping it.")
                    "\n" (dim "  Re-run with `bb quickstart --preset <name>` to reconfigure.")))

      :else
      (run-step 2 8 "Running configuration setup"
                ["bb" "setup"]))

    ;; Step 3: Validate configuration (critical — abort on failure)
    (run-step 3 8 "Validating configuration"
              ["bb" "doctor" "--ci"])

    ;; Step 4: Scaffold and integrate a sample module (non-critical — continue on failure)
    (let [scaffolded? (run-step 4 8 "Scaffolding sample module"
                                ["bb" "scaffold" "generate"
                                 "--module-name" "tasks" "--entity" "Task"
                                 "--field" "title:string" "--field" "done:boolean"]
                                :continue? true)]
      (when scaffolded?
        (run-step 5 8 "Integrating sample module into project"
                  ["bb" "scaffold" "integrate" "tasks"]
                  :continue? true)
        ;; Step 6: Activate module in config — the config key, which integrate also writes
        (println)
        (println (bold "[6/8] Activating sample module in config"))
        (if (inject-sample-module-config)
          (println (green "  Done"))
          (println (dim "  Skipped — could not inject config (add :wagoe/tasks manually)")))))

    ;; Step 7: Run migrations (critical — abort on failure)
    (run-step 7 8 "Running database migrations"
              ["bb" "migrate" "up"])

    ;; Step 8: Verify project structure
    (run-step 8 8 "Verifying project structure"
              ["bb" "smoke-check"])

    (print-success)))

;; Run when executed directly
(when (= *file* (System/getProperty "babashka.file"))
  (apply -main *command-line-args*))
