(ns wagoe.realtime.core.connection
  "Pure functions for WebSocket connection state management.
  
  Following FC/IS pattern - all functions are pure (no I/O).
  Connection lifecycle and authorization logic."
  (:require [wagoe.realtime.schema :as schema]
            [malli.core :as m]))

;; Connection State Management (Pure)

(defrecord Connection [id user-id roles metadata created-at])

(defn create-connection
  "Create new connection record.
  
  Pure function - deterministic for given inputs.
  
   Args:
    user-id - UUID of authenticated user
    roles - Set of user roles (keywords)
    metadata - Optional metadata map (default: {})
    id - Connection UUID generated by shell layer
    now - Current timestamp generated by shell layer
  
  Returns:
    Connection record"
  ([user-id roles id now]
   (create-connection user-id roles {} id now))
  ([user-id roles metadata id now]
   {:pre [(uuid? user-id)
          (set? roles)
          (every? keyword? roles)
          (map? metadata)
          (uuid? id)
          (inst? now)]}
   (map->Connection
    {:id id
     :user-id user-id
     :roles roles
     :metadata metadata
     :created-at now})))

(defn connection-age
  "Calculate connection age in seconds.
  
  Pure function - deterministic for given inputs.
  
  Args:
    connection - Connection record
    now - Current instant (for testability)
  
  Returns:
    Age in seconds"
  [connection now]
  {:pre [(instance? Connection connection)
         (inst? now)]}
  (let [created (:created-at connection)]
    (/ (.toMillis (java.time.Duration/between created now)) 1000.0)))

;; Authorization (Pure)

(defn authorize-connection?
  "Check if connection has required role.
  
  Pure function - no side effects.
  
  Args:
    connection - Connection record
    required-role - Role keyword required
  
  Returns:
    Boolean - true if connection has role"
  [connection required-role]
  {:pre [(instance? Connection connection)
         (keyword? required-role)]}
  (contains? (:roles connection) required-role))

(defn authorize-connection-any?
  "Check if connection has any of the required roles.
  
  Pure function - no side effects.
  
  Args:
    connection - Connection record
    required-roles - Set of role keywords
  
  Returns:
    Boolean - true if connection has at least one role"
  [connection required-roles]
  {:pre [(instance? Connection connection)
         (set? required-roles)
         (every? keyword? required-roles)]}
  (some (:roles connection) required-roles))

(defn authorize-connection-all?
  "Check if connection has all required roles.
  
  Pure function - no side effects.
  
  Args:
    connection - Connection record
    required-roles - Set of role keywords
  
  Returns:
    Boolean - true if connection has all roles"
  [connection required-roles]
  {:pre [(instance? Connection connection)
         (set? required-roles)
         (every? keyword? required-roles)]}
  (every? (:roles connection) required-roles))

;; Connection Filtering (Pure)

(defn filter-by-user
  "Filter connections by user ID.
  
  Pure function - no side effects.
  
  Args:
    connections - Collection of Connection records
    user-id - UUID to filter by
  
  Returns:
    Vector of matching connections"
  [connections user-id]
  {:pre [(uuid? user-id)]}
  (vec (filter #(= (:user-id %) user-id) connections)))

(defn filter-by-role
  "Filter connections by role.
  
  Pure function - no side effects.
  
  Args:
    connections - Collection of Connection records
    role - Role keyword to filter by
  
  Returns:
    Vector of connections with specified role"
  [connections role]
  {:pre [(keyword? role)]}
  (vec (filter #(contains? (:roles %) role) connections)))

(defn filter-by-metadata
  "Filter connections by metadata predicate.
  
  Pure function - no side effects.
  
  Args:
    connections - Collection of Connection records
    pred - Predicate function (metadata -> boolean)
  
  Returns:
    Vector of connections matching predicate"
  [connections pred]
  {:pre [(ifn? pred)]}
  (vec (filter #(pred (:metadata %)) connections)))

;; Connection Metadata Updates (Pure)

(defn update-metadata
  "Update connection metadata.
  
  Pure function - returns new connection, does not modify original.
  
  Args:
    connection - Connection record
    f - Function to apply to metadata (metadata -> new-metadata)
  
  Returns:
    New Connection record with updated metadata"
  [connection f]
  {:pre [(instance? Connection connection)
         (ifn? f)]}
  (update connection :metadata f))

(defn assoc-metadata
  "Associate key-value pair in connection metadata.
  
  Pure function - returns new connection.
  
  Args:
    connection - Connection record
    k - Metadata key
    v - Metadata value
  
  Returns:
    New Connection record with updated metadata"
  [connection k v]
  {:pre [(instance? Connection connection)]}
  (update connection :metadata assoc k v))

(defn dissoc-metadata
  "Dissociate key from connection metadata.
  
  Pure function - returns new connection.
  
  Args:
    connection - Connection record
    k - Metadata key to remove
  
  Returns:
    New Connection record with updated metadata"
  [connection k]
  {:pre [(instance? Connection connection)]}
  (update connection :metadata dissoc k))

;; Connection Validation (Pure)

(def ^:private connection-validator (m/validator schema/Connection))
(def ^:private connection-explainer (m/explainer schema/Connection))

(defn valid-connection?
  "Validate connection against schema.

  Pure function - no side effects.

  Args:
    connection - Connection record

  Returns:
    Boolean - true if valid"
  [connection]
  (connection-validator connection))

(defn explain-connection
  "Explain why connection is invalid.

  Pure function - returns validation errors.

  Args:
    connection - Connection record

  Returns:
    Malli explanation or nil if valid"
  [connection]
  (connection-explainer connection))
