--;; Runs no statement (BOU-576): every line carries migratus's separator,
--;; which it strips with the rest of the line.
--;;
--;; This created public.tenant_memberships in PostgreSQL-only SQL, so
--;; `migrate up` failed on SQLite and H2, and on a fresh PostgreSQL it made a
--;; table other than the one boot makes. The tenant library creates it at boot
--;; from its Malli schema. The id stays because existing databases have it
--;; applied.
