--;; Runs no statement (BOU-576): every line carries migratus's separator,
--;; which it strips with the rest of the line.
--;;
--;; This indexed users and user_sessions, which only boot creates, so
--;; `migrate up` failed on a database that had never booted. The user library
--;; creates both tables and their indexes at boot from its Malli schema. The
--;; id stays because existing databases have it applied.
